### ISSUE TITLE
Support setting ambient temperature

### ISSUE THREAD

**Issue by SeBsZ** [sHedC/python-masterthermconnect#19]
I know you're not at this stage yet, but eventually it would be nice of course if we could set the desired living room temperature through HomeAssistant.

I did some digging, and for the 2022 API here's the request that is made:

`POST hp_data https://mastertherm.online/api/v1/hp_data`

with form data:
```
messageId: 2
moduleId: xxxxx
deviceId: 1
variableId: A_210
variableValue: 17.5
```

Response received:
`{"timestamp":1670512072,"error":{"errorId":0,"errorMessage":""},"messageId":2,"data":{"data":{"001":{"A_210":"17.5"}}},"type":"read"}`

This sets register A_210 to a temperature of 17.5 degrees Celsius. As you know, from const.py, A_210 is the ambient_requested setting for hc0. We'll have to figure out how to best mark some of our registers in const.py as 'writeable' instead of just 'read-only'. For example, control_curves, ambient_requested, domestic_hot_water['required_temp'] are all writeable values.

**Comment by sHedC** [comment]
Available from the Command Line either using 
masterthermconnect set --username user --password pass --api-ver v2 reg module_id unit_id A_210 1
or
masterthermconnect set --username user --password pass --api-ver v2 data module_id unit_id heating_circuits.hc0.ambient_requested 17.5

Setting up alpha version 2.0.0a0
