### ISSUE TITLE
Let's fix some names and capitalizations

### ISSUE THREAD

**Issue by SeBsZ** [sHedC/python-masterthermconnect#34]
![image](https://user-images.githubusercontent.com/5457531/208096785-de0523d5-38f6-447a-8dee-6a4a14f2d738.png)
For example in this screenshot, I'm seeing most with a capital letter but 'heating' is uncapitalized. Same for 'winter'. Let's capitalize these?

Another one I mentioned is 'pump_running' for hc1-hc6, I don't think this is a correct name. Maybe valve_opened or something, but I can't verify that these work correctly since I don't have hc1-hc6 in use.

**Comment by sHedC** [comment]
The Case for Heating I think is just the translations, I didn't work out how to translate the HP Function select entity but think I have it now.

Agree perhaps the pump running to be changed to Circulation Pump?  This is what its called in the main heat-pump section.

**Comment by sHedC** [comment]
Changed the naming here, will fix the capitalizations in the HASS side under issue 2
