### ISSUE TITLE
Register for hc0 "on" can't be correct

### ISSUE THREAD

**Issue by SeBsZ** [sHedC/python-masterthermconnect#36]
![image](https://user-images.githubusercontent.com/5457531/208290962-1bcbd6c0-24ef-48d1-9246-520691a86f48.png)

**Comment by SeBsZ** [comment]
It seems to translate to register x_0 but this is undefined. I don't think there is an 'on' for hc0.

**Comment by sHedC** [comment]
I think as HC0 is the main pump the main switch is probably the on/off for it.
What about Ambient requested and Ambient temp is this from the thermostat?

Also the is a dhw_heating which goes to true when I am cycling hot water for the water and there is a dhw_on which is false for me, what about yours and can you change it on the app?

**Comment by SeBsZ** [comment]
I can not change anything regarding dhw in the app, only the set temp.
Ambient requested and ambient tmep are from the thermostat in the room, these are correct.
I just thought it was weird you made "on" for hc0 the same as the register for ambient_requested.

**Comment by sHedC** [comment]
No idea where the on came from, does nothing on mine everything is 0.  I will remove it.

**Comment by sHedC** [comment]
Should I get rid of the pad stuff and move into the main section for each HC if it makes sense? , in HC0 pad there is:
- Active - No idea what this really is or if we need it
- on - to remove
- temp - No idea what this represents
- temp_requested - again no idea.

For HC1/ 2 etc hopefully johny can help identify the thermostat settings here.

**Comment by sHedC** [comment]
I actually meant these :)
        "pad": {
            "active": ["bool", "D_242"],
            "enabled": ["bool", "D_182"],
            "temp": ["float", "A_190"],
            "temp_requested": ["float", "A_191"],
        },

**Comment by sHedC** [comment]
may be wrong but set 
HC0 - Got rid of On as is always on

HC0 - assume enabled if used
        "pad": {
            "active": ["fixed", True],  # No Register in the App
            "current_humidity": ["float", "I_185"],
            "requested_temp": ["float", "A_189"],
            "current_temp": ["float", "A_190"],
        },

HC1 -  
       "pad": {
            "active": ["bool", "D_245"],
            "current_humidity": ["float", "I_219"],
            "requested_temp": ["float", "A_219"],
            "current_temp": ["float", "A_220"],
        },

HC2 - Guessing
        "pad": {
            "active": ["bool", "D_248"],
            "current_humidity": ["float", "I_220"],  # Guess
            "requested_temp": ["float", "A_225"],
            "current_temp": ["float", "A_226"],
        },

  Will see how this works.
