### ISSUE TITLE
Python version issue

### ISSUE THREAD

**Issue by keytouch14** [sHedC/python-masterthermconnect#39]
Have done install, and it only installed version 0.1.0

I tried to install version 1.1.0-rc8 however it won't install as it requires python version 3.9 but my python is more advanced at version 3.11

Does it specifically need python 3.9 or does it need to check for 3.9 **or later**

With version 0.1.0, --list-device-reg does not work, I assume this is in later versions?

**Comment by sHedC** [comment]
I have a restriction from >=3.9, <3.11 as I was building for Home Assistant which uses 3.9 and 3.10 for supported versions.  I will try to update to allow also 3.11 will have to test it but my target will always be 3.10 until home assistant moves to the next python version.

Please would you put some detail on your setup, there are so many setups its confusing, for example I have a single heatpump with no connected thermostats (separate heating controls which were already there).  Also I have two optional circuits installed HC1 and HC2 for domestic hot water

Pump was installed in  2019 (there are two API versions now).

At the moment I only have 3 use cases and 2 are very similar so there is a lot of guess work going on :)

**Comment by keytouch14** [comment]
I'm only using python to test this out so I have downgraded to python 3.10
I have now installed version 1.1.0-rc8
--list-device-reg is now working for me

I'll pop my setup details on here later. Just wanted to quickly reply so you didn't waste your time checking python 3.11

**Comment by keytouch14** [comment]
Is there a command for looking at a particular register value? For example, can I make it show me just "I_12" rather than trawling through all the raw data each time?

**Comment by sHedC** [comment]
No worries I need to bump it to version 3.10 anyway as HASS is now min version of 3.10, I supposed I can put an option, I was thinking of putting a value after the display reg to show that as its a pain for me too.

**Comment by sHedC** [comment]
> Is there a command for looking at a particular register value? For example, can I make it show me just "I_12" rather than trawling through all the raw data each time?

Added this feature to issue #40
