### ISSUE TITLE
Connect error

### ISSUE THREAD

**Issue by valentapat** [sHedC/python-masterthermconnect#41]
masterthermconnect --api-ver v2, result = Connection Failed {"error":"invalid_grant","error_description":"Invalid user credentials"} 

## Version of the custom_component 
 tryed all versions

## Describe the bug
Can not connect into server  , username and password is correct

## Debug log
do not know were is debug
masterthermconnect --api-ver v2
Connection Failed {"error":"invalid_grant","error_description":"Invalid user credentials"}
```text

Add your logs here.
none
```

**Comment by SeBsZ** [comment]
Are you sure you need api version 2?

Op do 22 dec. 2022 12:00 schreef valentapat ***@***.***>:

**Comment by valentapat** [comment]
its the same 
Im try      masterthermconnect --user val***** --password ********                   
Connection Failed Invalid user name or password

**Comment by sHedC** [comment]
If you login using https://mastertherm.vip-it.cz/webui.php same credentials however if you are using the parameters for the user and password and have a space in the username please replace the space with a + and retry.

Old interface some usernames have spaces but those get converted to + but seems to fail if doing from the parameters.

**Comment by sHedC** [comment]
v1 - mastertherm.vip-it.cz is pre 2021 installs.

**Comment by valentapat** [comment]
I have new version,  mastertherm.online, username  conntains   "_" (underline), 
Is this problem ?

**Comment by sHedC** [comment]
No idea would have to debug to see what it sends, we will check it out, it is possible though.

**Comment by SeBsZ** [comment]
I just tried running

```
masterthermconnect --api-ver v2 --list-device-data --user myemail@gmail.com --password mypassword
```

and this works perfectly. But, my email and password doesn't contain any underline

**Comment by valentapat** [comment]
username I cannot change,  password contains    %

for more info:   homeassistant on synology in docker,  HASS also cannot connect, all I try . in docker terminal

**Comment by sHedC** [comment]
Its the %, it has to be encoded for URL,s I will do that please don't change it :)

**Comment by valentapat** [comment]
bash-5.1# masterthermconnect --api-ver v2 --list-device-data --user my_username --password mypass%x                                        
Connection Failed {"error":"invalid_grant","error_description":"Invalid user credentials"}                                                      
Traceback (most recent call last):                                                                                                              
  File "/usr/local/bin/masterthermconnect", line 8, in <module>                                                                                 
    sys.exit(main())                                                                                                                            
  File "/usr/local/lib/python3.10/site-packages/masterthermconnect/__main__.py", line 128, in main                                              
    devices = controller.get_devices()                                                                                                          
AttributeError: 'NoneType' object has no attribute 'get_devices'

**Comment by valentapat** [comment]
sorry - how correctly replace all files ? 

pip install masterthermconnect==1.1.0rc2 ??   rc8 ???

or any command for update?

**Comment by sHedC** [comment]
Sorry not yet deployed just doing some other updates then will implement an rc9 so install would be pip install masterthermconnect==1.1.0rc9

**Comment by sHedC** [comment]
Just published rc9, fingers crossed, the user and password transfer correctly so hopfully works.

**Comment by sHedC** [comment]
Its next on the list if I get a chance tonight I will, ignore the version on HASS until I do an official release all pre-releases are ignored.

HACS should just take the latest commit.  If I can do it before christmas I will do it tonight.

**Comment by valentapat** [comment]
I have not HACS, need only folder /custom_components/mastertherm/

**Comment by valentapat** [comment]
OT:  
- is it possible to execute commands? e.g. change temperature, on/off hot watter and save it.
- how can send this data into mqtt or run this script from node-red 
sorry and thanks

**Comment by sHedC** [comment]
Not yet that going to start looking at once I have a stable read.  Then was going to only allow changes that we can fully confirm :)

Build it up as its all guess work
