### ISSUE TITLE
Expose a variable called Operating mode for heating/ hot water or DHW

### ISSUE THREAD

**Issue by sHedC** [sHedC/python-masterthermconnect#9]
Alright, I found some more. I think we should put this in MasterThermConnect as well and expose it as a variable called Operating Mode. This is what the app/website uses to show the operating mode of the heat pump. Whether it is heating, cooling, heating for domestic hot water (DHW) or pool:

if (t.hp_functionTuv) {
    return "DHW"
} else {
    if (t.pool_v) {
        return "Pool"
    } else {
        if (t.someerror || t.threeerrors_v || !t.hp_Auxheater1OnOff) {
            if (t.hp_CoolingMode) {
                if (t.dewpcontrol_v) {
                    return "Dew point control"
                } else {
                    return "Cooling"
                }
            } else {
                return "Heating"
            }
        } else {
            return "Heating"
        }
    }
}
Let me know if you need the registers for dewpointcontrol and those errors

**Comment by SeBsZ** [comment]
Updated with our const.py variable names:

```
if (domestic_hot_water['function']) {
    return "DHW"
} else {
    if (pool_heating) {
        return "Pool"
    } else {
        if (error_info["some_error"] || error_info["three_errors"] || !aux_heater_1) {
            if (cooling_mode) {
                if (dewp_control) {
                    return "Dew point control"
                } else {
                    return "Cooling"
                }
            } else {
                return "Heating"
            }
        } else {
            return "Heating"
        }
    }
}
```
